
# ### Begin Transaction

# GET http://localhost:3000/transaction/?trans=2
# Content-Type: application/json
# authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ






### login for user 3000 port

POST http://localhost:3000/login/
Content-Type: application/json

{
    "email":"sambatharjunan@gmail.com",
    "password": "durai"
}



### getkey for user 3000 port

POST http://localhost:3000/login/getkey/sambatharjunan@gmail.com
Content-Type: application/json


### get all contacts for user uid

GET http://localhost:3000/allcontacts
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ

### insert contacts for user uid
POST http://localhost:3000/allcontacts
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ


[{"idUser":"24758","name":"A1234","initial":"Z","phone":"+919850889880"}

,{"idUser":"24758","name":"v1234","initial":"Z","phone":"+919850888880"}

,{"idUser":"25403","name":"D1234","initial":"A","phone":"+917332416405"}
]


### get callLog for user uid

GET http://localhost:3000/calllog
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ



### get details  for contact cid

GET http://localhost:3000/details/detailList?cid=3c08494a2ad184f
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ




### inser details  for contact cid

POST http://localhost:3000/details/insertdetails
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ


{
    "cid" : "3c08494a2ad184f",
    "name" : "Ganesh Durai 2",
    "msg" : "hi 2021" ,
    "problem" : "call",
    "nextplan" : "call",
    "place" : "call"

}


### update details  for contact cid

PUT http://localhost:3000/details/updetails/228
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ


{
    "cid" : "3c08494a2ad184f",
    "name" : "Ganesh Durai 2",
    "msg" : "hi 2021 januarrys" ,
    "problem" : "call",
    "nextplan" : "call",
    "place" : "call"

}




### get Goal from user uid

GET http://localhost:3000/goal?goaltype=1
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ




### insert Goal from user uid

POST http://localhost:3000/goal
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ


{
"uv": 8,
"plan": 1,
"info":5,
"parable":1,
"business":0,
"question":0,
"twentyfist":0,
"copycat":0,
"dvd":1,
"financial":0,
"welcome":1,
"qnet":0,
"earning":"39000",
"dream":"royal enfield",
"week":2,
"goal":0
}


### inser details  for contact cid

POST  http://localhost:3000/one108/
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ


{
    "feeling" : "GOOD",
    "knowledge" : "hi 2021" ,
    "activity" : "call",
    "nextdayplan" : "call",
    "goal" : "call",
    "nextdream" : "call"

}

### get profile  for contact cid

GET http://localhost:3000/profile/3c08494a2ad184f
Content-Type: application/json
authorization: Bearer eDyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjA5OTU4MDU2LCJleHAiOjE2MTAwNDQ0NTZ9.M0uuZQBgZPNxOdy_earjzDdbF-R7Udi8pI13Shpf-10




### insert profile  for contact cid

POST http://localhost:3000/profile/3c08494a2ad184f
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ



{
    "name" : "Ganesh Durai 2",
    "address" : "hi 2021" ,
    "job" : "amazon delivery",
    "sallery" : "call",
    "family" : "call",
    "country" : "call",
    "state" : "call",
    "place" : "call",
     "dtime" : "call"

}


### update profile  for contact cid

PUT http://localhost:3000/profile/3c08494a2ad184f
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ



{
    "name" : "Ganesh Durai 2",
    "address" : "hi 2021" ,
    "job" : "amazon delivery",
    "sallery" : "updated",
    "family" : "updated",
    "country" : "updated",
    "state" : "updated",
    "place" : "updated",
     "dtime" : "updated"

}


### get info   uid

GET http://localhost:3000/eightbasics/getInfoList/736c47e1770a6f9e04bd7fa9676227
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ




### get inwait  uid

GET http://localhost:3000/eightbasics/getInwaitList/736c47e1770a6f9e04bd7fa9676227
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ




### get plan  uid

GET http://localhost:3000/eightbasics/getPlanList/736c47e1770a6f9e04bd7fa9676227
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ





### get closer  uid

GET http://localhost:3000/eightbasics/getCloserList/736c47e1770a6f9e04bd7fa9676227
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ





### get dr  uid

GET http://localhost:3000/eightbasics/getDrList/736c47e1770a6f9e04bd7fa9676227
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ





### get rejected  uid

GET http://localhost:3000/eightbasics/getRejectedList/736c47e1770a6f9e04bd7fa9676227
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ




### insert 8basic  for contact cid

POST http://localhost:3000/eightbasics/
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ



{
    "cid" : "84325bbe34f0033",
    "basic" : 3 ,
    "percentage" : "60"
}


### update 8basic  for contact cid

PUT http://localhost:3000/eightbasics/
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ



{
    "cid" : "84325bbe34f0033",
    "basic" : 2 ,
    "percentage" : "40"
}


### Delete contact  using cid 
DELETE  http://localhost:3000/eightbasics/84325bbe34f0033
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ






### get  relationcontacts  using  uid

GET http://localhost:3000/relationship/736c47e1770a6f9e04bd7fa9676227
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ




### insert all relationcontacts using cids array

POST http://localhost:3000/relationship/
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ



[
    "d64d6a55b2fcddb",
    "d64d6a55b2fcddb"
    ]



### get trackingdetails  using uid 
GET  http://localhost:3000/getTrackingList/736c47e1770a6f9e04bd7fa9676227
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ





### get TimingDetails

GET http://localhost:3000/getTimingDetails/736c47e1770a6f9e04bd7fa9676227
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3MzZjNDdlMTc3MGE2ZjllMDRiZDdmYTk2NzYyMjciLCJuYW1lIjoic2FtYmF0aCIsImVtYWlsIjoic2FtYmF0aGFyanVuYW5AZ21haWwuY29tIiwiaWF0IjoxNjEwMDY5MzM3LCJleHAiOjE2MTAxNTU3Mzd9.6JUEgwLpIKlNI0Xb6ZkB2lCS8j7DasOeL-sPU9GL8SQ



{
   "from" : "2020-09-07 10:51:37.112549",
    "to" : "2021-09-15 23:51:37.112549",
     "category" : 9
}



###

POST  http://localhost:3000/restore/t8basic
Content-Type: application/json

###

POST  http://localhost:3000/restore/relation
Content-Type: application/json



###

POST  http://localhost:3000/restore/callLog
Content-Type: application/json



###

POST  http://localhost:3000/restore/contacts
Content-Type: application/json


###

POST  http://localhost:3000/restore/profile
Content-Type: application/json



###

POST  http://localhost:3000/restore/details
Content-Type: application/json


### login for user 

POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "sambath"
}




### logout for user

DELETE  http://localhost:4000/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic2FtIiwiaWF0IjoxNjA5NjU2MzM2fQ.iXFGFTIM2405mMnozsluMoqwuUWYHU3Dv2X-JY1Fhf4"
    
    
    }

### refreshess access token for user


POST http://localhost:4000/token
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic2FtYmF0aCIsImlhdCI6MTYwOTcxOTQzOH0.DSKCyT0JJWVSEJyqDgHxJ-k2Xg8ia0oxql4lAHSpzpk"
    }


### verify access token for user


GET http://localhost:4000/me
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic2FtYmF0aCIsImlhdCI6MTYwOTcxOTYwMX0.YI7uxV59k9i2n2hUmstGT0ApginNWGdzD1zZGh0KEnA

