
const cron = require("node-cron");

var path = require('path');
let nodemailer = require("nodemailer");

const Common =  class { 
    constructor() { 
      console.log("initialised");
    } 
    
    stask(count){

        const task = cron.schedule('*/1 * * * * *',()=>{
           //Foo the bar..
           Email();
           console.log(count+")printing data");
           count++;
           if(count >= 3){console.log("calling stop"); task.stop(); }
           
       });
       }
  }; 

  function Email(){

    var transporter = nodemailer.createTransport({
      service: 'gmail',
      host: 'smtp.gmail.com',
      auth: {
        user: "npmsambath@gmail.com", //generated by Mailtrap
        pass: "9790979908" //generated by Mailtrap
      }
    });
  
    transporter.verify(function(error, success) {
      if (error) {
          console.log(error);
      } else {
          console.log('Server is ready to take our messages');
      }
    });
  
    let mailOptions = {
      from: "npmsambath@gmail.com",
      to: "donsam1997@gmail.com",
      subject: `WEEK - 36 :Greating From Rest Server;)`,
      text: `Hi there, this email was automatically sent by us`,
      attachments: [
        {   // file on disk as an attachment
            filename: 'sample.txt',
            path: path.join(__dirname + '/sam.txt') // stream this file
        }
      ]
    };
    transporter.sendMail(mailOptions, function(error, info) {
      if (error) {
        throw error;
      } else {
        
        console.log("Email successfully sent!");
      }
    });
  
  }
module.exports =  Common