var MongoClient = require('mongodb').MongoClient;
var url = "mongodb://localhost:27017/";
let nodemailer = require("nodemailer");
var path = require('path');
const faker = require('faker');
const { User, Address } = require('../schema/user');



  


    // Display login page.
exports.showUsers =  function(req, res, next) {
        MongoClient.connect(url, function(err, db) {
            if (err) throw err;
            var dbo = db.db("nodedb");
            dbo.collection('users').aggregate([
              { $lookup:
                {
                  from: 'addresses',
                  localField: 'address',
                  foreignField: '_id',
                  as: 'addresdetails'
                }
              }
              ]).toArray(function(err, data) {
              if (err) throw err;
              console.log(JSON.stringify(data));
              res.send(data);
              db.close();
            });
          });
      };

exports.insertUsers =  function(request, response, next) {


if (request.session.loggedin) {	
            
      Email();
      inserData();
      
      response.send('Welcome back, ' + request.session.username + '!');
} else {
    response.send('Please login to view this page!');
}
response.end();
  };

function Email(){

  var transporter = nodemailer.createTransport({
    service: 'gmail',
    host: 'smtp.gmail.com',
    auth: {
      user: "npmsambath@gmail.com", //generated by Mailtrap
      pass: "9790979908" //generated by Mailtrap
    }
  });

  transporter.verify(function(error, success) {
    if (error) {
        console.log(error);
    } else {
        console.log('Server is ready to take our messages');
    }
  });

  let mailOptions = {
    from: "npmsambath@gmail.com",
    to: "donsam1997@gmail.com",
    subject: `WEEK - 36 :Greating From Rest Server;)`,
    text: `Hi there, this email was automatically sent by us`,
    attachments: [
      {   // file on disk as an attachment
          filename: 'sample.txt',
          path: path.join(__dirname + '/sam.txt') // stream this file
      }
    ]
  };
  transporter.sendMail(mailOptions, function(error, info) {
    if (error) {
      throw error;
    } else {
      console.log("Email successfully sent!");
    }
  });

}

function inserData(){

  const user = new User({
    name: faker.name.findName(),
    email: faker.internet.email()
});

user.save().then(userRef => {
    console.log(`${userRef.name} saved successfully`);
    const address = new Address({
        user: user._id,
        city: faker.address.city(),
        country: faker.address.country()
    })

    address.save()
    .then(addressRef => {
        console.log(`${userRef.name} lives in ${addressRef.city}`)
        userRef.address = addressRef._id
        userRef.save().then(_ => _)
    })
});
}